name: build
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: echo "::set-output name=matrix::{\"include\":[{'key':'1','name':'name-1'},{key:'2',name:'name-2'}]}"
  job2:
    needs: job1
    runs-on: ubuntu-latest
    strategy:
      matrix:
        test: ${{fromJson(needs.job1.outputs.matrix).include}}
    steps:
      - name: "wow"
        run: |
          echo "what"
          echo $${{matrix.test}}
          name=$${{matrix.test.name }}
          echo $name
